package com.codemetal.tapi.utils;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;

public class Utils {

	public static final char[] RANDOM_CHARSET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
			.toCharArray();
	public static final int RANDOM_UPPER_LIMIT = 9999;

	public static void main(String[] args) {
		RandomGenerate rGen = new RandomGenerate();
		int randomNum = rGen.generateRandomNumber();

		System.out.println("Generated Random Number is" + " : " + randomNum);
		System.out.println("------------------------------------------------");
		System.out.println("Current time as long" + " " + rGen.getCurrentTime());
		System.out.println("------------------------------------------------");
		System.out.println("Current Date in format dd/MM/yyyy" + " " + rGen.getCurrentDate("dd/MM/yyyy"));
		System.out.println("------------------------------------------------");
		System.out.println("Current Date in format MM/dd/yyyy" + " " + rGen.getCurrentDate("MM/dd/yyyy"));
		System.out.println("------------------------------------------------");
		System.out.println("Current Date in format yyyy/MM/dd" + " " + rGen.getCurrentDate("yyyy/MM/dd"));
		System.out.println("------------------------------------------------");
		System.out.println("Current Date in format yyyy-MMM-dd" + " " + rGen.getCurrentDate("yyyy-MMM-dd"));
		System.out.println("------------------------------------------------");
		System.out.println("Generated Randomstring of length 10 is" + " " + rGen.generateRandomString(10));
	}

}

class RandomGenerate {
	/**
	 * This method generates a random number between an upper and a lower bound
	 * value
	 * 
	 * @return the random number generated by the method
	 */
	public int generateRandomNumber() {
		int lower = 1;
		int upper = Utils.RANDOM_UPPER_LIMIT;
		int result = (int) (Math.random() * (upper - lower)) + lower;
		return result;
	}

	/**
	 * This method gives the current time in milliseconds
	 * 
	 * @return the current time in milliseconds
	 */
	public long getCurrentTime() {
		long currTime = System.currentTimeMillis();
		return currTime;
	}

	/**
	 * 
	 * @param format
	 *            the format according to which the current date should be
	 *            formatted and returned
	 * @return the current date formatted according to the given format
	 */
	public String getCurrentDate(String format) {
		SimpleDateFormat dateFormat = new SimpleDateFormat(format);
		return dateFormat.format(new Date());
	}

	/**
	 * 
	 * @param length
	 *            the required length of the random string that is to be
	 *            generated
	 * @return the random string generated with length equal to the specified
	 *         value.
	 */
	public String generateRandomString(int length) {
		char[] alphabetSet = Utils.RANDOM_CHARSET;
		Random random = new Random();
		StringBuffer out = new StringBuffer(length);
		for (int i = 0; i < length; i++) {

			int index = random.nextInt(alphabetSet.length);

			if (i == 0) {
				while (index <= 9) {
					index = random.nextInt(alphabetSet.length);
				}

			}

			out.append(alphabetSet[index]);

		}
		return out.toString();

	}

}
